site:
  base: https://namu.wiki
  genshin:
    character: https://namu.wiki/w/%EC%9B%90%EC%8B%A0/%EC%BA%90%EB%A6%AD%ED%84%B0
    weapon:
      swords: https://namu.wiki/w/%EC%9B%90%EC%8B%A0/%EB%AC%B4%EA%B8%B0/%ED%95%9C%EC%86%90%EA%B2%80
      claymores: https://namu.wiki/w/%EC%9B%90%EC%8B%A0/%EB%AC%B4%EA%B8%B0/%EC%96%91%EC%86%90%EA%B2%80
      polearms: https://namu.wiki/w/%EC%9B%90%EC%8B%A0/%EB%AC%B4%EA%B8%B0/%EC%9E%A5%EB%B3%91%EA%B8%B0
      catalysts: https://namu.wiki/w/%EC%9B%90%EC%8B%A0/%EB%AC%B4%EA%B8%B0/%EB%B2%95%EA%B5%AC
      bows: https://namu.wiki/w/%EC%9B%90%EC%8B%A0/%EB%AC%B4%EA%B8%B0/%ED%99%9C
  setting:
    except-keyword:
      - 원신/시스템/원소